name: Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
        
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Install vuepress
      run: |
        npm init
        cat package.json
        npm install -D vuepress@next
        npm install -D @vuepress/bundler-vite@next @vuepress/theme-default@next
      
    - name: Build
      run: |
        vuepress build docs

    - name: Push
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./docs/.vuepress/dist
        branch: gh-pages
