name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
        
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "20.x"

    - name: Install vuepress and build
      run: |
        npm install
        npm run docs:build

    - name: Push
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/.vuepress/dist
        branch: gh-pages
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
